)
# print(numpy_arr_2d ==2)
# print(numpy_arr_2d !=2)
# print(numpy_arr_2d >2)
# print(numpy_arr_2d <2)
# print(numpy_arr_2d >=2)
# print(numpy_arr_2d <=2)
# print(numpy_arr_2d & 2)
# print(numpy_arr_2d | 2)
# print(numpy_arr_2d ^ 2)
# print(numpy_arr_2d << 2)
# print(numpy_arr_2d >> 2)